on: [push, pull_request]

defaults:
  run:
    working-directory: ./tools/embark-oss

name: embark-oss CI
jobs:
  validate_projects:
    name: Validate projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: cargo fetch
      - run: cargo run check-maintainers --slack-webhook-url ${{ secrets.SLACK_WEBHOOK_URL }}
