on:
  schedule:
    # At 11:00 on every day-of-week from Monday through Friday. See https://crontab.guru/#0_11_*_*_1-5
    - cron: "0 11 * * 1-5"

name: embark-oss CI
jobs:
  validate_projects:
    name: Validate projects
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: cargo fetch
      - run: cargo build
      # server-framework is still in development and not ready to be listed on
      # the website
      - run: cargo run validate-all --slack-webhook-url ${{ secrets.SLACK_WEBHOOK_URL }} --github-api-token ${{ secrets.GITHUB_TOKEN }} --skip server-framework
